import streamlit as st
import urllib.parse
from st_supabase_connection import SupabaseConnection

st.title("🛠️ Admin: Form Builder")
conn = st.connection("supabase", type=SupabaseConnection)

admin_email = st.session_state.user_email

# --- GENERATE SHAREABLE LINK ---
# We encode the email so symbols like '@' become URL-safe
safe_email = urllib.parse.quote(admin_email)
# Note: "Take_Survey" is the URL path generated by Streamlit based on your router.py page title
shareable_link = f"http://localhost:8501/?admin={safe_email}"

st.info(f"🔗 **Your Unique Survey Link:**\n\n[{shareable_link}]({shareable_link}) \n\n*Copy and send this link to your commuters!*")
st.divider()

def fetch_my_questions():
    try:
        # FILTER: Only fetch questions where admin_email matches the logged-in user!
        res = conn.client.table("form_questions").select("*").eq("admin_email", admin_email).order("id").execute()
        return res.data
    except Exception:
        return []

form_schema = fetch_my_questions()

st.header("Add a New Question")
col1, col2, col3 = st.columns([2, 1, 1])
with col1:
    new_prompt = st.text_input("Question Text")
with col2:
    q_type = st.selectbox("Question Type", ["Short Answer", "Paragraph", "Multiple Choice", "Rating (1-5)"])
with col3:
    st.write("") 
    st.write("") 
    is_demographic = st.checkbox("👥 Demographic?")

new_options = []
if q_type == "Multiple Choice":
    opts = st.text_input("Enter options separated by commas (e.g., Good, Bad, Okay)")
    if opts:
        new_options = [o.strip() for o in opts.split(",")]
        
if st.button("➕ Add Question"):
    if new_prompt:
        # ADD THE ADMIN EMAIL HERE
        new_q = {
            "prompt": new_prompt, 
            "q_type": q_type, 
            "options": new_options, 
            "is_demographic": is_demographic,
            "admin_email": admin_email  
        }
        conn.client.table("form_questions").insert(new_q).execute()
        st.success("Question added permanently!")
        st.rerun() 
        
st.divider()
st.header("Your Form Questions")
if len(form_schema) == 0:
    st.info("You haven't added any questions yet.")
    
for i, q in enumerate(form_schema):
    c1, c2 = st.columns([4, 1])
    demo_badge = " *(👥 Demographic)*" if q.get('is_demographic') else ""
    c1.write(f"**{i+1}. {q['prompt']}** *(Type: {q['q_type']})*{demo_badge}")
    
    if c2.button("❌ Delete", key=f"del_{q['id']}"):
        conn.client.table("form_questions").delete().eq("id", q['id']).execute()
        st.rerun()